USE [master]
GO

/****** Object:  Database [BackEndAPI]    Script Date: 4/26/2018 4:03:55 PM ******/
CREATE DATABASE [BackEndAPI]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BackEndAPI', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\BackEndAPI.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BackEndAPI_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\BackEndAPI_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [BackEndAPI] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BackEndAPI].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BackEndAPI] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BackEndAPI] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BackEndAPI] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BackEndAPI] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BackEndAPI] SET ARITHABORT OFF 
GO

ALTER DATABASE [BackEndAPI] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BackEndAPI] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BackEndAPI] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BackEndAPI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BackEndAPI] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BackEndAPI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BackEndAPI] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BackEndAPI] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BackEndAPI] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BackEndAPI] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BackEndAPI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BackEndAPI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BackEndAPI] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BackEndAPI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BackEndAPI] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BackEndAPI] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BackEndAPI] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BackEndAPI] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BackEndAPI] SET  MULTI_USER 
GO

ALTER DATABASE [BackEndAPI] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BackEndAPI] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BackEndAPI] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BackEndAPI] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BackEndAPI] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BackEndAPI] SET QUERY_STORE = OFF
GO

USE [BackEndAPI]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [BackEndAPI] SET  READ_WRITE 
GO


